name: tw_business_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  google_nav_bar: ^5.0.3
  firebase_image: ^1.0.1
  intl: ^0.17.0
  nfc_in_flutter: ^2.0.5
  animations: ^2.0.0
  badges: ^2.0.1
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.1.0
  http: ^0.13.3
  google_place: ^0.4.0
  qr_code_scanner: ^0.5.2
  rflutter_alert: ^2.0.2
  qr_flutter: ^4.0.0
  #charts_flutter: ^0.11.0
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  easy_localization: ^3.0.0
  get: ^4.3.8
  url_launcher: ^6.0.9
  device_info_plus: ^3.1.1
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.8


  flutter_nfc_plugin:
    path: ./flutter-nfc-plugin

  firebase_storage: ^8.0.1
  image_picker: ^0.8.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  image_path: "assets/icon/logo_business.png"
  adaptive_icon_background: "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/
    - assets/images/
    - assets/images/sticker.png
    - assets/res/terms_and_conditions.txt
    - assets/res/privacy_policy.txt
    - assets/images/success.png
    - assets/images/fail.png
    - assets/translations/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
